[package]
name = "rust_gpio_handler"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"

[lib]
name = "gpio_lib"
path = "src/lib.rs"

[[bin]]
name = "check_gpio"
path = "src/main.rs"

[dependencies]
rppal = {version = "0.14.1"}
